---
apiVersion: v1
kind: Pod
metadata:
  name: kisio-vault-agent
spec:
  serviceAccountName: vault-auth
  restartPolicy: Never

  volumes:
    - name: vault-token
      emptyDir:
        medium: Memory

    - name: config
      configMap:
        name: kisio-vault-agent-config
        items:
          - key: vault-agent-config.hcl
            path: vault-agent-config.hcl

          - key: consul-template-config.hcl
            path: consul-template-config.hcl

    - name: shared-data
      emptyDir: {}

    - name: nginx-data
      hostPath :
        path : /tmp/kube-vault-nginx
        type : Directory

  initContainers:
    # Vault container
    - name: vault-agent-auth
      image: vault

      volumeMounts:
        - name: config
          mountPath: /etc/vault
        - name: vault-token
          mountPath: /home/vault

      # This assumes Vault running on local host and K8s running in Minikube using VirtualBox
      env:
        - name: VAULT_ADDR
          value: http://192.168.42.1:8200

      # Run the Vault agent
      args:
        [
          "agent",
          "-config=/etc/vault/vault-agent-config.hcl",
          #"-log-level=debug",
        ]

  containers:
    # RHSSO Container
    # - name: hofund-rhsso
    #   image: docker-registry.canaltp.fr/kisiodigital/hofund-rhsso:7.3-1

    #   ports:
    #     - containerPort: 8080

    #   env:
    #     - name: DB_VENDOR
    #       value: ${DB_VENDOR}
    #     - name: DB_ADDR
    #       value: ${DB_ADDR}
    #     - name: DB_DATABASE
    #       value: ${DB_DATABASE}
    #     - name: DB_USER
    #       value: ${DB_USER}
    #     - name: DB_PASSWORD
    #       value: ${DB_PASSWORD}
    #     - name: RHSSO_USER
    #       value: ${RHSSO_USER}
    #     - name: RHSSO_PASSWORD
    #       value: ${RHSSO_PASSWORD}

    # Consul Template container
    - name: consul-template
      image: hashicorp/consul-template:alpine
      imagePullPolicy: Always

      volumeMounts:
        - name: vault-token
          mountPath: /home/vault

        - name: config
          mountPath: /etc/consul-template

        - name: shared-data
          mountPath: /etc/secrets

      env:
        - name: HOME
          value: /home/vault

        - name: VAULT_ADDR
          value: http://192.168.42.1:8200

      # Consul-Template looks in $HOME/.vault-token, $VAULT_TOKEN, or -vault-token (via CLI)
      args:
        [
          "-config=/etc/consul-template/consul-template-config.hcl",
          # "-log-level=debug",
        ]

    # Nginx container
    - name: nginx-container
      image: nginx

      ports:
        - containerPort: 80

      volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html/

        - name: shared-data
          mountPath: /usr/share/nginx/html/secrets/